import crypto from 'crypto';

export const SAMPLE_COMMUNITY_REPORTS = [
  // --- CLUSTER 1: Ward 14 Stormwater Drainage & Road Degradation (High Density Hotspot) ---
  {
    category: 'Water',
    description: 'Severe waterlogging near Main Road intersection after 20 mins of rain. Depth exceeding 1.5 feet.',
    duration: 'A few weeks',
    recurrence: 'Almost always',
    severity: 'Dangerous',
    isRiskPresent: 1,
    riskDescription: 'Two wheelers skidding into open drains hidden under water',
    latitude: 19.0760,
    longitude: 72.8777,
    source: 'exif',
    address: 'Ward 14 West, Main Road Junction, Mumbai',
    city: 'Mumbai',
    status: 'In Progress',
    civic_priority_score: 88,
    daysAgo: 1,
  },
  {
    category: 'Roads',
    description: 'Deep potholes and bitumen erosion along 200m stretch adjacent to the flooded intersection.',
    duration: 'A few weeks',
    recurrence: 'Frequently',
    severity: 'Serious',
    isRiskPresent: 1,
    riskDescription: 'Traffic bottleneck and rim damage for small vehicles',
    latitude: 19.0768,
    longitude: 72.8783,
    source: 'manual',
    address: 'Ward 14 West, 2nd Cross Road, Mumbai',
    city: 'Mumbai',
    status: 'Action Scheduled',
    civic_priority_score: 79,
    daysAgo: 2,
  },
  {
    category: 'Sanitation',
    description: 'Sub-surface stormwater culvert choked with plastic waste and silt, causing backflow onto road.',
    duration: 'A few months',
    recurrence: 'Almost always',
    severity: 'Serious',
    isRiskPresent: 0,
    latitude: 19.0754,
    longitude: 72.8769,
    source: 'device',
    address: 'Ward 14 West, Municipal Canal Lane, Mumbai',
    city: 'Mumbai',
    status: 'Assigned',
    civic_priority_score: 82,
    daysAgo: 3,
  },
  {
    category: 'Water',
    description: 'Drain water entering ground floor residential compounds and basement car park.',
    duration: 'A few days',
    recurrence: 'Frequently',
    severity: 'Dangerous',
    isRiskPresent: 1,
    riskDescription: 'Electrical meters submerged in basement',
    latitude: 19.0763,
    longitude: 72.8790,
    source: 'device',
    address: 'Ward 14 West, Sunrise Apartments, Mumbai',
    city: 'Mumbai',
    status: 'Under Review',
    civic_priority_score: 91,
    daysAgo: 1,
  },
  {
    category: 'Water',
    description: 'Manhole cover displaced by water pressure during morning surge.',
    duration: 'Today',
    recurrence: 'Sometimes',
    severity: 'Dangerous',
    isRiskPresent: 1,
    riskDescription: 'Unmarked open manhole in submerged road',
    latitude: 19.0772,
    longitude: 72.8770,
    source: 'exif',
    address: 'Ward 14 West, Station Approach Road, Mumbai',
    city: 'Mumbai',
    status: 'In Progress',
    civic_priority_score: 95,
    daysAgo: 0,
  },

  // --- CLUSTER 2: Dadar Central Market Sanitation & Electrical Surge ---
  {
    category: 'Electricity',
    description: 'Low-hanging transformer lines sparking near vegetable market canopy.',
    duration: 'A few days',
    recurrence: 'Frequently',
    severity: 'Dangerous',
    isRiskPresent: 1,
    riskDescription: 'Live wire in pedestrian crowded market zone',
    latitude: 19.0178,
    longitude: 72.8478,
    source: 'manual',
    address: 'Dadar Market Road, Central Zone, Mumbai',
    city: 'Mumbai',
    status: 'Assigned',
    civic_priority_score: 89,
    daysAgo: 2,
  },
  {
    category: 'Sanitation',
    description: 'Uncleared vegetable market garbage heap blocking pedestrian sidewalk and drainage gutter.',
    duration: 'A few days',
    recurrence: 'Almost always',
    severity: 'Moderate',
    isRiskPresent: 0,
    latitude: 19.0185,
    longitude: 72.8469,
    source: 'device',
    address: 'Dadar Flower Market Lane, Mumbai',
    city: 'Mumbai',
    status: 'In Progress',
    civic_priority_score: 72,
    daysAgo: 4,
  },
  {
    category: 'Water',
    description: 'Drinking water pipeline joint leak spraying onto electrical pole junction.',
    duration: 'A few weeks',
    recurrence: 'Frequently',
    severity: 'Serious',
    isRiskPresent: 1,
    riskDescription: 'Electrification hazard near wet pavement',
    latitude: 19.0172,
    longitude: 72.8485,
    source: 'exif',
    address: 'Dadar Station East Road, Mumbai',
    city: 'Mumbai',
    status: 'Under Review',
    civic_priority_score: 84,
    daysAgo: 1,
  },
  {
    category: 'Sanitation',
    description: 'Overflowing public community bin attracting stray animals and blocking lane entry.',
    duration: 'Today',
    recurrence: 'Frequently',
    severity: 'Moderate',
    isRiskPresent: 0,
    latitude: 19.0190,
    longitude: 72.8475,
    source: 'manual',
    address: 'Dadar Kabutar Khana Circle, Mumbai',
    city: 'Mumbai',
    status: 'Submitted',
    civic_priority_score: 65,
    daysAgo: 0,
  },

  // --- CLUSTER 3: Bandra Hill Road Pedestrian & School Safety ---
  {
    category: 'Schools',
    description: 'Missing pedestrian zebra crossing and broken school zone speed breaker near St. Anne Convent.',
    duration: 'A few months',
    recurrence: 'Almost always',
    severity: 'Serious',
    isRiskPresent: 1,
    riskDescription: 'Vehicles speeding during school dismissal hours',
    latitude: 19.0558,
    longitude: 72.8315,
    source: 'exif',
    address: 'Bandra Hill Road, St. Anne Zone, Mumbai',
    city: 'Mumbai',
    status: 'Resolved',
    civic_priority_score: 78,
    daysAgo: 8,
  },
  {
    category: 'Roads',
    description: 'Broken concrete sidewalk pavers with exposed reinforcement rebar in front of primary school gate.',
    duration: 'A few weeks',
    recurrence: 'First time',
    severity: 'Moderate',
    isRiskPresent: 1,
    riskDescription: 'Tripping hazard for young children',
    latitude: 19.0562,
    longitude: 72.8320,
    source: 'device',
    address: 'Bandra Hill Road, School Lane, Mumbai',
    city: 'Mumbai',
    status: 'Confirmed Resolved',
    civic_priority_score: 70,
    daysAgo: 12,
  },
  {
    category: 'Electricity',
    description: 'Streetlights malfunctioning on school access lane, creating total pitch darkness after 7 PM.',
    duration: 'A few weeks',
    recurrence: 'Almost always',
    severity: 'Moderate',
    isRiskPresent: 0,
    latitude: 19.0552,
    longitude: 72.8308,
    source: 'manual',
    address: 'Bandra Hill Road, Church Bypass, Mumbai',
    city: 'Mumbai',
    status: 'Assigned',
    civic_priority_score: 66,
    daysAgo: 5,
  },

  // --- CLUSTER 4: Andheri Subway Monsoon Basin (Critical Hotspot) ---
  {
    category: 'Water',
    description: 'Andheri Subway waterlogging reaching 4 feet under railway bridge during high tide.',
    duration: 'A few months',
    recurrence: 'Almost always',
    severity: 'Dangerous',
    isRiskPresent: 1,
    riskDescription: 'Vehicles trapped under subway bridge',
    latitude: 19.1197,
    longitude: 72.8464,
    source: 'exif',
    address: 'Andheri Subway, S.V. Road Junction, Mumbai',
    city: 'Mumbai',
    status: 'In Progress',
    civic_priority_score: 96,
    daysAgo: 1,
  },
  {
    category: 'Roads',
    description: 'Subway approach ramps severely pitted with exposed gravel after stormwater recedes.',
    duration: 'A few weeks',
    recurrence: 'Frequently',
    severity: 'Serious',
    isRiskPresent: 1,
    riskDescription: 'Sudden braking causing rear-end collisions',
    latitude: 19.1205,
    longitude: 72.8472,
    source: 'device',
    address: 'Andheri West Approach, Mumbai',
    city: 'Mumbai',
    status: 'Action Scheduled',
    civic_priority_score: 83,
    daysAgo: 2,
  },
  {
    category: 'Sanitation',
    description: 'Stormwater pump suction sump blocked by accumulated industrial plastic bags and silt.',
    duration: 'A few days',
    recurrence: 'Almost always',
    severity: 'Dangerous',
    isRiskPresent: 1,
    riskDescription: 'Emergency dewatering pumps failing due to suction choke',
    latitude: 19.1190,
    longitude: 72.8458,
    source: 'manual',
    address: 'Andheri Pump House Sump, Mumbai',
    city: 'Mumbai',
    status: 'Assigned',
    civic_priority_score: 92,
    daysAgo: 1,
  },
];
